runtime: python38
entrypoint: gunicorn -b :$PORT docsearch.api.search:api
service: docsearch

runtime_config:
  python_version: 3

env_variables:
  REDIS_HOST: "dracula.dev"
  REDIS_PASSWORD: "!YH?r%BP,)2xm,H:UU"

# Low-cost test settings -- delete when live.
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10