version: "3.8"

services:
  app:
    build: .
    environment:
      PORT: 8080
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_HOST: "localhost"
    ports:
      - "6379:6379"
      - "8080:8080"

  test:
    build: .
    entrypoint: "pytest"
