version: "3.8"

services:
  app:
    build: .
    ports:
      - "6379:6379"
      - "8080:8080"
    volumes:
      - $PWD/data:/data
    env_file:
      - .env

  test:
    build: .
    entrypoint: "pytest"
    env_file:
      - .env

